# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Stage 1: Build the application
FROM node:18-alpine AS builder

# Create app directory
WORKDIR /app

# Copy package.json and package-lock.json for npm install
COPY package*.json ./

# Install dependencies, including devDependencies for building
RUN npm install

# Copy the source code
COPY src ./src
COPY tsconfig.json ./

# Build the project
RUN npm run build

# Stage 2: Run the application
FROM node:18-alpine

# Create app directory
WORKDIR /app

# Copy only necessary files
COPY --from=builder /app/build /app/build
COPY --from=builder /app/package*.json ./

# Install only production dependencies
RUN npm ci --only=production

# SENDGRID_API_KEY must be passed at runtime (e.g. -e SENDGRID_API_KEY=...).
# Do NOT bake a default — the server hard-fails on startup if missing,
# which is correct, but a placeholder default would mask configuration errors.

# Specify the command to run
ENTRYPOINT ["node", "build/index.js"]
